// Re-export all workout types from shared — single source of truth
export type {
  SetType,
  WeightUnit,
  DistanceUnitSystem,
  DistanceUnitUS,
  DistanceUnitMetric,
  DistanceUnit,
  ExerciseCategory,
  WorkoutMode,
  GroupType,
  GroupSetType,
  SupersetMode,
  GoalType,
  Set,
  Exercise,
  ExerciseGroup,
  ExerciseItem,
  Note,
  SessionNote,
  Workout,
  SupersetSelection,
  GroupSelectionMode,
  RestTimer,
  FlatExerciseRow,
  RestPeriodSetInfo,
  FocusNextSet,
  ExerciseStats,
  ExerciseLibraryItem,
  ExerciseStatsMap,
  UserSettings,
  BodyMeasurement,
  UserGoal,
  PersonalRecord,
  UserProfile,
  DashboardData,
} from '@shared/types/workout';
