-- Add is_scorable, is_default, is_advanced to muscles and motions.
-- Defaults: is_scorable = TRUE, is_default = TRUE, is_advanced = FALSE.

ALTER TABLE muscles ADD COLUMN IF NOT EXISTS is_scorable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE muscles ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE muscles ADD COLUMN IF NOT EXISTS is_advanced BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE motions ADD COLUMN IF NOT EXISTS is_scorable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE motions ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE motions ADD COLUMN IF NOT EXISTS is_advanced BOOLEAN NOT NULL DEFAULT FALSE;
